name: Test Filefly

on:
  pull_request:
    types:
      - opened
      - edited
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker test container
      run: docker build -t madeofpendletonwool/filefly-test . -f dockerfile-test
      
    - name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v3
      with:
        image: madeofpendletonwool/filefly-test:latest
        severity_threshold: HIGH

    - name: Run tests in the Docker container
      run: docker run madeofpendletonwool/filefly-test